[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:dein#enable_notification = 1
'''

# ----- tools ----- #
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
"inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
let g:asyncomplete_remove_duplicates = 1
let g:asyncomplete_smart_completion = 1
let g:asyncomplete_auto_popup = 1

autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'natebosch/vim-lsc'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
augroup MyLsp
    autocmd!
    " goplsだと、大文字始まりで文字列を2文字入力したときに補完ダイアログが閉じてしまう&大文字1文字を入力した後に補完候補を選択すると、入力した文字が消えてしまう問題が起こる
    if executable('bingo')
        au User lsp_setup call lsp#register_server({
            \ 'name': 'bingo',
            \ 'cmd': {server_info->['bingo', '-mode', 'stdio']},
            \ 'whitelist': ['go'],
            \ })
        autocmd FileType go call s:configure_lsp()
    endif

    " https://kashewnuts.github.io/2019/01/28/move_from_jedivim_to_vimlsp.html よりコピペ
    if executable('pyls')
        " pip install python-language-server
        au User lsp_setup call lsp#register_server({
            \ 'name': 'pyls',
            \ 'cmd': {server_info->['pyls']},
            \ 'whitelist': ['python'],
            \ 'workspace_config': {'pyls': {'plugins': {
            \   'pycodestyle': {'enabled': v:false},
            \   'jedi_definition': {'follow_imports': v:true, 'follow_builtin_imports': v:true},}}}
            \})
        autocmd FileType python call s:configure_lsp()
    endif
augroup END

function! s:configure_lsp() abort
    setlocal omnifunc=lsp#complete   " オムニ補完を有効化
    " LSP用にマッピング
    nnoremap <buffer> <C-]> :<C-u>LspDefinition<CR>
    nnoremap <buffer> gd :<C-u>LspDefinition<CR>
    nnoremap <buffer> gD :<C-u>LspReferences<CR>
    nnoremap <buffer> gs :<C-u>LspDocumentSymbol<CR>
    nnoremap <buffer> gS :<C-u>LspWorkspaceSymbol<CR>
    nnoremap <buffer> gQ :<C-u>LspDocumentFormat<CR>
    vnoremap <buffer> gQ :LspDocumentRangeFormat<CR>
    nnoremap <buffer> K :<C-u>LspHover<CR>
    nnoremap <buffer> <F1> :<C-u>LspImplementation<CR>
    nnoremap <buffer> <F2> :<C-u>LspRename<CR>
endfunction
" let g:lsp_diagnostics_enabled = 0  " 警告やエラーの表示はALEに任せるのでOFFにする
let g:lsp_async_completion = 1
'''
depends = ['async.vim']

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
let g:go_bin_path = "$GOPATH/bin"
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1

let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
let g:go_auto_sameids = 1

let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0
'''

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
\   'go': ['go vet', 'gofmt', 'goimports', 'golint'],
\   'python': ['flake8'],
\}
let g:ale_fixers = {
\   'javascript': ['prettier'],
\ }
let g:ale_fix_on_save = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = "!!"
let g:ale_sign_warning = ">>"
highlight clear ALEErrorSign
highlight clear ALEWarningSign
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
let g:sonictemplate_vim_template_dir = '$HOME/repo/dotfiles/vim/template'
'''

[[plugins]]
repo = 'aklt/plantuml-syntax'
hook_add = '''
let g:plantuml_executable_script = '$HOME/.plantuml'
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_cmd = 'CtrlPMRU'
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
augroup PrevimSettings
    autocmd!
    autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*,pml} set filetype=markdown
augroup END
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
let g:NERDTreeDirArrows = 1
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'qpkorr/vim-bufkill'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
nmap n <Plug>(anzu-n-with-echo)
nmap N <Plug>(anzu-N-with-echo)
nmap * <Plug>(anzu-star-with-echo)
nmap # <Plug>(anzu-sharp-with-echo)
nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
'''

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
let g:memolist_path = '$HOME/repo/memolist/'
nmap <Leader>mn :MemoNew<CR>
nmap <Leader>ml :MemoList<CR>
nmap <Leader>mg :MemoGrep<CR>
nmap <Leader>mf :CtrlP g:memolist_path<CR>
'''

# ----- visual ----- #
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:webdevicons_conceal_nerdtree_brackets = 1
let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
let g:DevIconsEnableFoldersOpenClose = 1
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
set laststatus=2
function! FilePath()
    if winwidth(0) > 90
        return expand("%:s")
    else
        return expand("%:t")
    endif
endfunction
let g:lightline = {
    \   'mode_map': {
    \      'c': 'COMMAND',
    \      'i': 'INSERT',
    \      'n': 'NORMAL',
    \      's': 'SELECT',
    \      't': 'TERMINAL',
    \      'v': 'VISUAL',
    \      'R': 'REPLACE',
    \      'S': 'S-LINE',
    \      'V': 'V-LINE',
    \      "\<C-s>": 'S-BLOCK',
    \      "\<C-v>": 'V-BLOCK',
    \   },
    "\   'colorscheme': 'powerline',
    \   'colorscheme': 'PaperColor',
    \   'component_function': {
    \      'filepath': 'FilePath',
    \      'gitbranch': 'fugitive#head',
    \      'anzu': 'anzu#search_status'
    \   },
    \   'component_type': {
    \      'tabs': 'tabsel',
    \      'close': 'raw' 
    \   },
    \   'tabline': {
    \      'left': [['tabs']],
    \      'right': [['close']]
    \   },
    \   'active': {
    \      'left': [['mode', 'paste'], ['readonly', 'filepath', 'modified', 'gitbranch']],
    \      'right': [['percent', 'lineinfo'], ['linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok']],
    \   },
    \   'inactive': {
    \      'left': [['filepath', 'modified', 'gitbranch']],
    \      'right': [['percent', 'lineinfo']],
    \   },
    \ }
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
let g:lightline.component_expand = {
    \  'linter_checking': 'lightline#ale#checking',
    \  'linter_warnings': 'lightline#ale#warnings',
    \  'linter_errors': 'lightline#ale#errors',
    \  'linter_ok': 'lightline#ale#ok',
    \ }
let g:lightline.component_type = {
    \     'linter_checking': 'left',
    \     'linter_warnings': 'warning',
    \     'linter_errors': 'error',
    \     'linter_ok': 'left',
    \ }
'''

## ----- colorscheme ----- ##
[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
set background=light
set termguicolors
let ayucolor="light"
colorscheme ayu
"autocmd MyAutoCmd VimEnter * nested hi MatchParen ctermfg=green ctermbg=black
'''
